# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            TiDB
tagline:          'TiDB Weekly'
description:      'TiDB is a distributed SQL database. Inspired by the design of Google F1, TiDB supports the best features of both traditional RDBMS and NoSQL.'
url:              http://weekly.pingcap.com
baseurl:          ""

author:
  name:           'PingCAP'
  url:            https://www.pingcap.com

paginate:         5

# Custom vars
version:          Beta20160730

github:
  repo:           https://github.com/pingcap/tidb

